import React, { useEffect, useState } from 'react';
import { api } from '../../services/api';
import { ImpactStats } from '../../types';
import { CountUpNumber } from '../common/CountUpNumber';
import { Leaf, DollarSign, Clock, Sparkles } from 'lucide-react';

export const ImpactCounterSection: React.FC = () => {
  const [impact, setImpact] = useState<ImpactStats>({
    money_saved_inr: 49400,
    waste_diverted_kg: 118.2,
    tutoring_hours: 98.5,
    exchanges_count: 82,
    karma_circulated: 3480,
  });

  useEffect(() => {
    api.getCampusImpact()
      .then((data) => setImpact(data))
      .catch(() => {});
  }, []);

  const stats = [
    {
      label: 'Student Money Saved',
      value: impact.money_saved_inr,
      prefix: '₹',
      suffix: '',
      decimals: 0,
      icon: DollarSign,
      color: 'text-amber-400',
      detail: 'Estimated textbook & gear costs prevented',
    },
    {
      label: 'Campus Waste Diverted',
      value: impact.waste_diverted_kg,
      prefix: '',
      suffix: ' kg',
      decimals: 1,
      icon: Leaf,
      color: 'text-emerald-400',
      detail: 'E-waste and physical goods recirculated',
    },
    {
      label: 'Peer Tutoring Delivered',
      value: impact.tutoring_hours,
      prefix: '',
      suffix: ' hrs',
      decimals: 1,
      icon: Clock,
      color: 'text-sky-400',
      detail: '1-on-1 mentorship & project guidance',
    },
    {
      label: 'Karma Points Circulated',
      value: impact.karma_circulated,
      prefix: '',
      suffix: '',
      decimals: 0,
      icon: Sparkles,
      color: 'text-amber-300',
      detail: 'Non-monetary value created on campus',
    },
  ];

  return (
    <section className="py-24 border-t border-slate-800 bg-surface/30">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="text-center max-w-2xl mx-auto mb-14">
          <span className="text-xs font-mono uppercase tracking-widest text-emerald-400 font-bold">
            Live Sustainability & Economic Telemetry
          </span>
          <h2 className="text-3xl sm:text-4xl font-extrabold text-white mt-2 tracking-tight">
            Measurable Campus Impact
          </h2>
          <p className="text-xs sm:text-sm text-slate-400 mt-2">
            Real-time aggregate impact generated by SRM students exchanging without fiat currency.
          </p>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
          {stats.map((item, idx) => {
            const Icon = item.icon;
            return (
              <div
                key={idx}
                className="p-6 rounded-2xl glass-panel relative overflow-hidden group hover:border-slate-700 transition-colors"
              >
                <div className="flex items-center justify-between mb-4">
                  <span className="text-xs font-mono text-slate-400 uppercase tracking-wider">
                    {item.label}
                  </span>
                  <div className="p-2 rounded-lg bg-slate-900 border border-slate-800">
                    <Icon className={`w-4 h-4 ${item.color}`} />
                  </div>
                </div>

                <div className="text-3xl sm:text-4xl font-extrabold text-white font-mono tracking-tight my-2">
                  <CountUpNumber
                    value={item.value}
                    prefix={item.prefix}
                    suffix={item.suffix}
                    decimals={item.decimals}
                  />
                </div>

                <p className="text-[11px] text-slate-400 mt-2">{item.detail}</p>
              </div>
            );
          })}
        </div>
      </div>
    </section>
  );
};
